Repository FEUP-ESOF-2020-21/open-cx-t4g5-teenage-mutant-coding-turtles, pull requests merged in 2020-12, with the labels that each got.

#29 domain model
  docs/Development-Report.md
  docs/images/domain-model.png
  src/netfair/.dart_tool/package_config.json
  src/netfair/.packages
Labels: documentation, iteration2

#30 Create event Screen
  src/netfair/.gitignore
  src/netfair/lib/create_event_screen.dart
  src/netfair/lib/landing_screen.dart
  src/netfair/lib/login_screen.dart
  src/netfair/lib/main.dart
  src/netfair/lib/sign_up_screen.dart
Labels: enhancement, iteration3

#33 Backend
  .gitignore
  docs/Development-Report.md
  docs/images/domain-model.png
  docs/images/use_cases.png
  domain-model.drawio
  src/netfair/.dart_tool/package_config.json
  src/netfair/.packages
  src/netfair/android/app/build.gradle
  src/netfair/android/build.gradle
Labels: enhancement, iteration3

#36 Profile scren
  src/netfair/assets/feupcarrerfair.jpg
  src/netfair/lib/event_profile_screen.dart
  src/netfair/lib/landing_screen.dart
  src/netfair/lib/main.dart
  src/netfair/pubspec.lock
  src/netfair/pubspec.yaml
Labels: enhancement, iteration3

#41 create profile screen
  src/netfair/assets/fonts/Comfortaa-Bold.ttf
  src/netfair/assets/fonts/Comfortaa-Light.ttf
  src/netfair/assets/fonts/Comfortaa-Medium.ttf
  src/netfair/assets/fonts/Comfortaa-Regular.ttf
  src/netfair/assets/fonts/Comfortaa-SemiBold.ttf
  src/netfair/assets/fonts/Comfortaa-VariableFont_wght.ttf
  src/netfair/assets/img/app_logo.jpg
  src/netfair/assets/img/app_logo.png
  src/netfair/assets/img/app_logo_cropped.jpg
  src/netfair/assets/img/events/feupcarrerfair.jpg
  src/netfair/assets/img/users/terryCrews.jpg
  src/netfair/lib/Components/CreateEventWizard.dart
  src/netfair/lib/Components/CreateProfileWizard.dart
  src/netfair/lib/Components/EventTile.dart
  src/netfair/lib/Components/LoginForm.dart
  src/netfair/lib/Components/MyAppBar.dart
  src/netfair/lib/Components/MyBottomNavigationBar.dart
  src/netfair/lib/Components/MyTextFieldDatePicker.dart
  src/netfair/lib/Components/RegisterForm.dart
  src/netfair/lib/Decorations/text_field_decor.dart
  src/netfair/lib/Screens/choose_user_type_screen.dart
  src/netfair/lib/Screens/create_event_screen.dart
  src/netfair/lib/Screens/create_profile_screen.dart
  src/netfair/lib/Screens/event_profile_screen.dart
  src/netfair/lib/Screens/landing_screen.dart
  src/netfair/lib/Screens/login_screen.dart
  src/netfair/lib/Screens/profile_screen.dart
  src/netfair/lib/Screens/sign_up_screen.dart
  src/netfair/lib/create_event_screen.dart
  src/netfair/lib/landing_screen.dart
  src/netfair/lib/login_screen.dart
  src/netfair/lib/main.dart
  src/netfair/lib/profile_screen.dart
  src/netfair/lib/sign_up_screen.dart
  src/netfair/pubspec.lock
  src/netfair/pubspec.yaml
Labels: enhancement, iteration3

#43 Removed tag
  src/netfair/lib/main.dart
Labels: enhancement, iteration3

#46 Cleaning up
  .idea/modules.xml
  .idea/open-cx-t4g5-teenage-mutant-coding-turtles.iml
  .idea/vcs.xml
  .idea/workspace.xml
  domain-model.drawio
  src/.idea/.gitignore
  src/.idea/libraries/Dart_Packages.xml
  src/.idea/libraries/Dart_SDK.xml
  src/.idea/libraries/gradle_wrapper.xml
  src/.idea/libraries/gradle_wrapper2.xml
  src/.idea/libraries/gradle_wrapper3.xml
  src/.idea/libraries/libs.xml
  src/.idea/libraries/libs2.xml
  src/.idea/libraries/libs3.xml
  src/.idea/libraries/out.xml
  src/.idea/libraries/out2.xml
  src/.idea/libraries/out3.xml
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/src.iml
  src/.idea/vcs.xml
Labels: enhancement, iteration3

#47 End of Iteration 3, frontend is ready
  .gitignore
  src/netfair/.dart_tool/package_config.json
  src/netfair/.gitignore
  src/netfair/.packages
  src/netfair/android/app/build.gradle
  src/netfair/android/app/google-services.json
  src/netfair/android/build.gradle
  src/netfair/assets/fonts/Comfortaa-Bold.ttf
  src/netfair/assets/fonts/Comfortaa-Light.ttf
  src/netfair/assets/fonts/Comfortaa-Medium.ttf
  src/netfair/assets/fonts/Comfortaa-Regular.ttf
  src/netfair/assets/fonts/Comfortaa-SemiBold.ttf
  src/netfair/assets/fonts/Comfortaa-VariableFont_wght.ttf
  src/netfair/assets/img/app_logo.jpg
  src/netfair/assets/img/app_logo.png
  src/netfair/assets/img/app_logo_cropped.jpg
  src/netfair/assets/img/events/feupcarrerfair.jpg
  src/netfair/assets/img/users/terryCrews.jpg
  src/netfair/lib/Components/CreateEventWizard.dart
  src/netfair/lib/Components/CreateProfileWizard.dart
  src/netfair/lib/Components/EventTile.dart
  src/netfair/lib/Components/LoginForm.dart
  src/netfair/lib/Components/MyAppBar.dart
  src/netfair/lib/Components/MyBottomNavigationBar.dart
  src/netfair/lib/Components/MyTextFieldDatePicker.dart
  src/netfair/lib/Components/RegisterForm.dart
  src/netfair/lib/Decorations/text_field_decor.dart
  src/netfair/lib/Screens/choose_user_type_screen.dart
  src/netfair/lib/Screens/create_event_screen.dart
  src/netfair/lib/Screens/create_profile_screen.dart
  src/netfair/lib/Screens/event_profile_screen.dart
  src/netfair/lib/Screens/landing_screen.dart
  src/netfair/lib/Screens/login_screen.dart
  src/netfair/lib/Screens/profile_screen.dart
  src/netfair/lib/Screens/sign_up_screen.dart
  src/netfair/lib/landing_screen.dart
  src/netfair/lib/login_screen.dart
  src/netfair/lib/main.dart
  src/netfair/pubspec.lock
  src/netfair/pubspec.yaml
Labels: iteration3

#57 Authentication
  src/netfair/lib/Components/LoginForm.dart
  src/netfair/lib/Components/RegisterForm.dart
  src/netfair/lib/Screens/login_screen.dart
  src/netfair/lib/Screens/wrapper.dart
  src/netfair/lib/main.dart
  src/netfair/pubspec.lock
  src/netfair/pubspec.yaml
Labels: Iteration4, enhancement

#59 Added Sign Out
  src/netfair/lib/Components/MyAppBar.dart
Labels: Iteration4, enhancement

#60 Database models
  src/netfair/lib/Components/CreateProfileWizard.dart
  src/netfair/lib/Models/database.dart
  src/netfair/lib/Models/event.dart
  src/netfair/lib/Models/user.dart
Labels: Iteration4, enhancement

#63 Profile backend, closes #50
  src/netfair/lib/Components/CreateProfileWizard.dart
  src/netfair/lib/Components/MyAppBar.dart
  src/netfair/lib/Models/user.dart
Labels: Iteration4, enhancement

#65 Added a user model toJson test, to start testing
  src/netfair/test/widget_test.dart
Labels: Iteration4, Testing

#66 Github action
  flutter.yml
Labels: Testing
